/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    @DisplayName("Grade 70 should return true for passing")
    void testPassingGrade() {
        LehmanGradeBook gb = new LehmanGradeBook();
        assertTrue(gb.isPassing(70), "A grade of 70 should pass.");
        assertEquals('A', gb.getLetterGrade(95));
        assertEquals('F', gb.getLetterGrade(50));
        assertEquals('A', gb.getLetterGrade(90));
        assertEquals('B', gb.getLetterGrade(80));
        assertEquals('C', gb.getLetterGrade(70));
    }
}
